`timescale 1ns/1ps

module tb_nor_gate;

reg a, b;
wire y;

nor_gate uut (
    .a(a),
    .b(b),
    .y(y)
);

initial begin
    $display("Time\tA\tB\tY");
    $monitor("%0t\t%b\t%b\t%b", $time, a, b, y);

    a = 0; b = 0; #10;
    a = 0; b = 1; #10;
    a = 1; b = 0; #10;
    a = 1; b = 1; #10;

    $finish;
end

endmodule
